### ISSUE TITLE
RN 0.72.3 compile issue

### ISSUE THREAD

**Issue by sn4f** [sendbird/react-native-scrollview-enhancer#6]
Hello, could you help me with this one?

```
> Task :sendbird_react-native-scrollview-enhancer:compileDebugKotlin FAILED
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
e: /app/node_modules/@sendbird/react-native-scrollview-enhancer/android/src/main/java/com/scrollviewenhancer/MaintainVisibleScrollPositionHelper.kt: (60, 1): Class 'MaintainVisibleScrollPositionHelper' is not abstract and does not implement abstract member public abstract fun willMountItems(p0: UIManager!): Unit defined in com.facebook.react.bridge.UIManagerListener
```

**Comment by bang9** [comment]
Hi @sn4f starting from version 0.72.0 and later, React-Native provides all the features(onStartReached, maintainVisibleContentPosition) in FlatList, so you do not need this library.

**Comment by sn4f** [comment]
@bang9 thanks

**Comment by Jtmaca9** [comment]
Ive just run into this same problem, it really should be removed from the introduction documentation if it is not required anymore.

**Comment by bang9** [comment]
@Jtmaca9 Hi, we provide a [note](https://sendbird.com/docs/chat/uikit/v3/react-native/introduction/send-first-message#2-get-started-3-step-2-install-uikit-and-the-required-dependencies) for this.

<img width="802" alt="image" src="https://github.com/sendbird/react-native-scrollview-enhancer/assets/26326015/d589bcec-073b-4a10-b736-eb8f0098a4f6">

---

As a library provider, we need to consider users who are using versions below 0.72.
At the time of the 0.75 release, as we will have sufficiently moved away from the 0.72 version, we plan to update the note as follows. 

> Note: If you're using React-Native 0.71.x or lower, you should install `@sendbird/react-native-scrollview-enhancer`.
